name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: macos-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set Git user information (email and name)
      - name: Set Git User
        run: |
          git config --global user.name "Pranesh G"
          git config --global user.email "prans1991@gmail.com"

      # Run version bump (adjust the action as per your choice)
      - name: Bump version
        uses: mathieudutour/github-tag-action@v5
        with:
          skip_commit: false # This will commit the version bump change

      # Optionally, push changes and create a tag
      - name: Push changes
        run: |
          git push
          git push --tags
