name: Version Bump

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js (required if you're using npm/yarn)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify your desired Node.js version

      # Set Git user information (using your GitHub email and username)
      - name: Set Git User
        run: |
          git config --global user.name "Pranesh G"
          git config --global user.email "prans1991@gmail.com"

      # Bump version in package.json
      - name: Bump version
        run: |
          npm version minor -m "CI Bump version to %s"

      # Commit and push changes
      - name: Push changes
        run: |
          git push origin HEAD:master
          git push --tags  # Push the created tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
